__app_name__ = "UsCmdRelay"
__package_name__ = "uscmdrelay"
__version__ = "0.1.2"
__description__ = "A lightweight command relay server"
__author__ = "Septimiu Ujica"
__author_email__ = "me@septi.ro"
__author_url__ = "https://www.septi.ro"
__license__ = "GPLv3"
