APP_NAME = "UsCmdRelay"
APP_VERSION = "0.1.2"
APP_DESCRIPTION = "A lightweight command relay server"
APP_AUTHOR = "Septimiu Ujica"
APP_AUTHOR_EMAIL = "me@septi.ro"
APP_AUTHOR_URL = "https://www.septi.ro"